feat: Use SP1 prover directly (#413)
* chore: Replace Sphinx with SP1

* chore: Minor cleanup and fix benches

Removes the PrimeField32 bound where unnecessary

* fix: Use Arcs and remove some expensive clones

This impacts mainly long computations with a lot of sharding (see
lair_shard_test) and large matrices, or large lair programs

* chore: Minor cleanup

* feat: Update to SP1 v4+, temporarily disable sharding

After SP1 v4, the global lookup argument for cross-shard chip
communication was drastically redesigned, which means our currently
implementation is temporarily broken. See #437. The proper solution will
require a proper design for sharded Lurk computation.

This commit also removes all of the now-unnecessary dummy chips, since
only single-shard computations can be proven right now.

* chore: Address clippy

* chore: Temporarily disable `bench-regression` CI

* chore: Remove debug cargo patches

---------

Co-authored-by: wwared <541936+wwared@users.noreply.github.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -74,100 +74,100 @@ jobs:
       # TODO: Uncomment once https://github.com/EmbarkStudios/cargo-deny-action/issues/67 is released
       # - name: Cargo-deny
       #   uses: EmbarkStudios/cargo-deny-action@v1
-  
-  bench-regression:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          repository: argumentcomputer/ci-workflows
-      - uses: ./.github/actions/ci-env
-      - uses: actions/checkout@v4
-      - uses: dtolnay/rust-toolchain@stable
-      - uses: Swatinem/rust-cache@v2
-      - uses: taiki-e/install-action@nextest
-      - name: Set env
-        run: |
-          echo "TESTS=fib_e2e"  | tee -a $GITHUB_ENV
-          echo "LOAM_FIB_ARG=50000" | tee -a $GITHUB_ENV
-      - name: Get benchmark for PR
-        id: bench_pr
-        run: |
-          BENCH_RESULTS='[]'
 
-          for test_name in ${{ env.TESTS }}; do
-            cargo nextest run -E "test($test_name)" --release --nocapture --run-ignored all | tee out.txt 2>&1
-            BENCH=$(grep 'Total time' out.txt | awk -F'= ' '{ print $2 }')
-            BENCH_RESULTS=$(echo $BENCH_RESULTS | jq -c ". += [{\"${test_name}\": \"$BENCH\"}]")
-          done
+  # TODO: Uncomment once the github token works correctly with `JasonEtco/create-an-issue@v2`
+  # bench-regression:
+  #   enabled:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         repository: argumentcomputer/ci-workflows
+  #     - uses: ./.github/actions/ci-env
+  #     - uses: actions/checkout@v4
+  #     - uses: dtolnay/rust-toolchain@stable
+  #     - uses: Swatinem/rust-cache@v2
+  #     - uses: taiki-e/install-action@nextest
+  #     - name: Set env
+  #       run: |
+  #         echo "TESTS=fib_e2e"  | tee -a $GITHUB_ENV
+  #         echo "LOAM_FIB_ARG=50000" | tee -a $GITHUB_ENV
+  #     - name: Get benchmark for PR
+  #       id: bench_pr
+  #       run: |
+  #         BENCH_RESULTS='[]'
 
-          echo "BENCH_RESULTS=$BENCH_RESULTS" | tee -a "$GITHUB_OUTPUT"
-      - uses: actions/checkout@v4
-        with:
-          ref: ${{ github.base_ref }}
-      - name: Get bench for base branch
-        id: regression-check
-        continue-on-error: false
-        run: |
-          counter=0
-          BENCH_RESULTS='${{ steps.bench_pr.outputs.BENCH_RESULTS }}'
-          echo "$BENCH_RESULTS"
-          SLOW_TESTS=""
-          REGRESSION="false"
+  #         for test_name in ${{ env.TESTS }}; do
+  #           cargo nextest run -E "test($test_name)" --release --nocapture --run-ignored all | tee out.txt 2>&1
+  #           BENCH=$(grep 'Total time' out.txt | awk -F'= ' '{ print $2 }')
+  #           BENCH_RESULTS=$(echo $BENCH_RESULTS | jq -c ". += [{\"${test_name}\": \"$BENCH\"}]")
+  #         done
 
-          for test_name in ${{ env.TESTS }}; do
-            cargo nextest run -E "test($test_name)" --release --nocapture --run-ignored all | tee out.txt 2>&1
-            BENCH_BASE=$(grep 'Total time' out.txt | awk -F'= ' '{ print $2 }')
-            BENCH_PR=$(echo "$BENCH_RESULTS" | jq ".[$counter] | to_entries | .[0].value" | sed 's/"//g')
+  #         echo "BENCH_RESULTS=$BENCH_RESULTS" | tee -a "$GITHUB_OUTPUT"
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         ref: ${{ github.base_ref }}
+  #     - name: Get bench for base branch
+  #       id: regression-check
+  #       continue-on-error: false
+  #       run: |
+  #         counter=0
+  #         BENCH_RESULTS='${{ steps.bench_pr.outputs.BENCH_RESULTS }}'
+  #         echo "$BENCH_RESULTS"
+  #         SLOW_TESTS=""
+  #         REGRESSION="false"
 
-            echo "$test_name summary"
-            echo "Base = $BENCH_BASE, PR = $BENCH_PR"
+  #         for test_name in ${{ env.TESTS }}; do
+  #           cargo nextest run -E "test($test_name)" --release --nocapture --run-ignored all | tee out.txt 2>&1
+  #           BENCH_BASE=$(grep 'Total time' out.txt | awk -F'= ' '{ print $2 }')
+  #           BENCH_PR=$(echo "$BENCH_RESULTS" | jq ".[$counter] | to_entries | .[0].value" | sed 's/"//g')
 
-            if [[ -z $BENCH_BASE || -z $BENCH_PR ]]; then
-              exit 1
-            fi
+  #           echo "$test_name summary"
+  #           echo "Base = $BENCH_BASE, PR = $BENCH_PR"
 
-            BENCH_BASE_NUM=${BENCH_BASE%% *}
-            BENCH_PR_NUM=${BENCH_PR%% *}
+  #           if [[ -z $BENCH_BASE || -z $BENCH_PR ]]; then
+  #             exit 1
+  #           fi
 
-            # 10% slowdown threshold
-            REGRESSION_THRESHOLD=$(echo "$BENCH_BASE_NUM * 1.10" | bc)
+  #           BENCH_BASE_NUM=${BENCH_BASE%% *}
+  #           BENCH_PR_NUM=${BENCH_PR%% *}
 
-            if (( $(echo "$BENCH_PR_NUM >= $REGRESSION_THRESHOLD" | bc -l) )); then
-              echo "Performance regression for test ${test_name}"
-              REGRESSION="true"
-              SLOW_TESTS+="\`${test_name}\`\n"
-              SLOW_TESTS+="Bench result before: $BENCH_BASE\n"
-              SLOW_TESTS+="Bench result after: $BENCH_PR\n"
-            fi
-            counter=$((counter + 1))
-          done
+  #           # 10% slowdown threshold
+  #           REGRESSION_THRESHOLD=$(echo "$BENCH_BASE_NUM * 1.10" | bc)
 
-          echo "regression=$REGRESSION" | tee -a $GITHUB_OUTPUT
-          echo "slow-tests<<EOF" >> $GITHUB_OUTPUT
-          echo -e "$SLOW_TESTS" | tee -a $GITHUB_OUTPUT
-          echo "EOF" >> $GITHUB_OUTPUT
-          echo "WORKFLOW_URL=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" | tee -a $GITHUB_ENV
-      - uses: actions/checkout@v4
-      - name: Comment on failing run
-        if: steps.regression-check.outputs.regression == 'true' && github.event_name == 'pull_request'
-        uses: peter-evans/create-or-update-comment@v4
-        with:
-          issue-number: ${{ github.event.pull_request.number }}
-          body: |
-            Benchmark regression check failed :x:
+  #           if (( $(echo "$BENCH_PR_NUM >= $REGRESSION_THRESHOLD" | bc -l) )); then
+  #             echo "Performance regression for test ${test_name}"
+  #             REGRESSION="true"
+  #             SLOW_TESTS+="\`${test_name}\`\n"
+  #             SLOW_TESTS+="Bench result before: $BENCH_BASE\n"
+  #             SLOW_TESTS+="Bench result after: $BENCH_PR\n"
+  #           fi
+  #           counter=$((counter + 1))
+  #         done
 
-            ${{ steps.regression-check.outputs.slow-tests }}
+  #         echo "regression=$REGRESSION" | tee -a $GITHUB_OUTPUT
+  #         echo "slow-tests<<EOF" >> $GITHUB_OUTPUT
+  #         echo -e "$SLOW_TESTS" | tee -a $GITHUB_OUTPUT
+  #         echo "EOF" >> $GITHUB_OUTPUT
+  #         echo "WORKFLOW_URL=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" | tee -a $GITHUB_ENV
+  #     - uses: actions/checkout@v4
+  #     - name: Comment on failing run
+  #       if: steps.regression-check.outputs.regression == 'true' && github.event_name == 'pull_request'
+  #       uses: peter-evans/create-or-update-comment@v4
+  #       with:
+  #         issue-number: ${{ github.event.pull_request.number }}
+  #         body: |
+  #           Benchmark regression check failed :x:
 
-            [Workflow URL](${{ env.WORKFLOW_URL }})
-      - uses: JasonEtco/create-an-issue@v2
-        if: steps.regression-check.outputs.regression == 'true' && github.event_name == 'merge_group'
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          WORKFLOW_URL: ${{ env.WORKFLOW_URL }}
-          SLOW_TESTS: ${{ steps.regression-check.outputs.slow-tests }}
-        with:
-          update_existing: true
-          filename: .github/BENCH_REGRESSION.md
- 
+  #           ${{ steps.regression-check.outputs.slow-tests }}
 
+  #           [Workflow URL](${{ env.WORKFLOW_URL }})
+  #     - uses: JasonEtco/create-an-issue@v2
+  #       if: steps.regression-check.outputs.regression == 'true' && github.event_name == 'merge_group'
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #         WORKFLOW_URL: ${{ env.WORKFLOW_URL }}
+  #         SLOW_TESTS: ${{ steps.regression-check.outputs.slow-tests }}
+  #       with:
+  #         update_existing: true
+  #         filename: .github/BENCH_REGRESSION.md
